### ISSUE TITLE
Problem with Stata variable name completion.

### ISSUE THREAD

**Issue by Lknb** [statatmbundle/Stata.tmbundle#10]
Whenever I try to use variable name completion, I get the error: 

> Traceback (most recent call last):
>   File "Complete Varname", line 12, in <module>
>     word = os.environ['TM_CURRENT_WORD']
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in **getitem**
>     raise KeyError(key)
> KeyError: 'TM_CURRENT_WORD' 

I am using TextMate 2.0 and Stata12. 

Any help is appreciated.

**Comment by pschumm** [comment]
As I have not heard of any reports of this problem with Stata 13 or higher, I am closing this issue.
