### ISSUE TITLE
Issues with STATA 14

### ISSUE THREAD

**Issue by scunning1975** [statatmbundle/Stata.tmbundle#12]
I recently upgraded to STATA 14, and now when I run a do file from within Textmate 2, it brings up a temporary do file (which still doesn't work properly).  Not sure how to troubleshoot it.

**Comment by pschumm** [comment]
I'm going to need more information than what you've written here.  For example, quit Stata (all instances), open a do-file in TextMate, and hit `cmd-R`.  This _should_ launch Stata and run the do-file; note that you will see a line at the top of the output like

```
. do "/Users/<username>/<project_path>/.tm-stata-19396.do"
```

where `<username>` is your username and `<project_path>` is the path to your project.  If this is not what happens for you, please explain what _does_ happen and, if possible, attach the output you get in Stata's Results window.

**Comment by pschumm** [comment]
One more thing—this may be what's causing your trouble.  Go into Stata's Preferences, and under Windows -> Do-file Editor -> Advanced, make sure that "Edit do-files opened from the Finder in Do-file Editor" is _unchecked_.  That may be what's causing your problem, although that setting existed under Stata 13, and should have been unchanged following your upgrade (unless you replaced your old preferences file).

**Comment by scunning1975** [comment]
That did it!  Thank you so much.  I was really hoping that there was a workaround.
