### ISSUE TITLE
Feature request: End strings on line-end, rather than matching quotes

### ISSUE THREAD

**Issue by karldw** [statatmbundle/Stata.tmbundle#13]
Stata lets you end strings by just moving to the next line, without closing the quotes, like this:

```stata
disp "This is a valid statement.
* Just a comment, not part of the string on the previous line.
disp "Here's another statement without closing quote.
* Here's how comments are supposed to be colored, now
* that the syntax highlighter knows the quote is closed.
```

Currently Github's syntax coloring, which I think is based on this TextMate bundle, looks for matching quotes.  The lines above make Github think the comment in the second line is included as part of the string.

Could Stata.tmbundle be changed to color strings by the same rules Stata does, where strings can be terminated by both closing quotes _and_ line-ends?

**Comment by pschumm** [comment]
AFAICT, this is a quirk of `display` (possibly unintended), and is certainly not true in general, e.g.,

```stata
. loc foo "Hello world!
invalid syntax
r(198);

. set obs 1
number of observations (_N) was 0, now 1

. gen foo = "Hello world!
too few quotes
r(132);
```

Thus, even if we wanted to make this change to be consistent with Stata's own behavior, we'd be doing it for `display` only. My personal feeling is that this behavior is a misfeature, and string literals should be surrounded by quotes (in Stata, these being double quotes or compound double quotes).

I'll leave this open for now in case you'd like to make a case for why we should do this, but if not, will close this issue.

**Comment by karldw** [comment]
Ah, I didn't realize it was a `display`-exclusive quirk.  I agree, it doesn't make sense to have a special case.  Thanks!
